name: deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker build
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          tags: vazhnyvpnbot:latest
          build-args: |
            "bot_token=${{ secrets.BOT_TOKEN }}"
            "database_url=${{ vars.DATABASE_URL }}"
            "outline_api_url=${{ vars.OUTLINE_API_URL }}"
            "outline_api_cert=${{ secrets.OUTLINE_API_CERT }}"
            "admin_password=${{ secrets.ADMIN_PASSWORD }}"
      - name: docker compose
        run: docker compose up -d