name: deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: docker build
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: vazhnyvpnbot:latest
      - name: stop and remove old containers
        run: docker-compose -f docker-compose.yml down
      - name: deploy
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          OUTLINE_API_URL: ${{ vars.OUTLINE_API_URL }}
          OUTLINE_API_CERT: ${{ secrets.OUTLINE_API_CERT }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: docker-compose -f docker-compose.yml up -d
