name: deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker build
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          tags: vazhnyvpnbot:latest
      - name: docker run
        run: docker run -d --rm vazhnyvpnbot --name vazhnyvpnbot \
          -v /mnt/g/dev/vaszhnyvpnbot/app/database/db.sqlite3:/opt/vazhnyvpnbot/database/db.sqlite3 vazhnyvpnbot \
          --env BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
          --env DATABASE_URL=${{ secrets.DATABASE_URL }} \
          --env OUTLINE_API_URL=${{ secrets.OUTLINE_API_URL }} \
          --env OUTLINE_API_CERT=${{ secrets.OUTLINE_API_CERT }} \
          --env ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \